# Generated by Django 5.0 on 2025-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartsImage",
            fields=[
                (
                    "shirt_parts_image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("shirt_parts_id", models.CharField(max_length=100)),
                ("file_path", models.ImageField(upload_to="parts_image/")),
                ("component_name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "shirt_parts_images",
            },
        ),
    ]
